### ISSUE TITLE
display at iphone 5/SE 10.3.1 with new cart widget inline=true

### ISSUE THREAD

**Issue by helua** [commercelayer/mfe-microstore#63]
### Describe the bug

I know it's kinda retro model, just letting you know that the cart model does not fit to 320px width screen 
![obraz](https://github.com/commercelayer/mfe-microstore/assets/37885634/51632d4b-3fb2-46b0-803b-69c27a331814)
Have a good day!
Andrzej Helio

### To Reproduce

I used the latest version from 17/6/2024

### System

iphone 5/SE 10.3.1

**Comment by gciotola** [comment]
Thanks @helua! This has been fixed.
